services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_DATABASE}
      - MYSQL_USER=${MYSQL_DB_USER}
      - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-net

volumes:
  mysql-data:

networks:
  mysql-net:
    driver: bridge
